### PR TITLE
Add the actual command that generated the .cs file in the comments

### PR DESCRIPTION
**Pull request by 0xced**
Your colleagues and your future self will be happy to know exactly all the parameters that were used during generation when the C# source code must be regenerated for whatever reason.

Before:
```csharp
// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
```

After:
```csharp
// This code was generated by XmlSchemaClassGenerator version 1.0.0.0 using the following command:
// xscgen --namespace http://microsoft.com/schemas/VisualStudio/TeamTest/2010=vstst --collectionSettersMode=Public --collectionType=System.Array --nullable --pcl --verbose vstst.xsd
```

### CODE REVIEW

**Comment by mganss** [comment]
Good idea. I'd prefer this to be output only if a corresponding flag is enabled, though.

Also, this only works if the code is generated through xscgen. Perhaps the command line string could be passed as a configuration property into the library, allowing library consumers to create their own custom string. If it's null, the string will be built from environment.

**Comment by 0xced** [comment]
I addressed your comments with a slightly different approach in fe3b230. The comment is added by default **when run from** `xcsgen` or `XmlSchemaClassGenerator.Console` only. Otherwise, consumers of the library must explicitly set `GenerateCommandLineArgumentsComment` to `true`. It's also possible for the consumers of the library to replace the `CommandLineArgumentsProvider` on the generator with a custom subclass that overrides the `CommandLineArgumentsProvider.CommandLineArguments` property if desired.

**Comment by mganss** [comment]
Thanks. Could you create a another test or two to fix the coverage?

**Comment by 0xced** [comment]
> Could you create another test or two to fix the coverage?

Done in 62681c044aa9824fcceef8e698bcae7da1c1b095

**Comment by 0xced** [comment]
Excellent, thanks for merging!

Are you going to publish the packages on nuget.org too? Both [XmlSchemaClassGenerator-beta][1] and [dotnet-xscgen][2] are stuck at version 2.0.521 on NuGet even though there are [4 releases listed on GitHub][3] since version 2.0.521.

[1]: https://www.nuget.org/packages/XmlSchemaClassGenerator-beta/
[2]: https://www.nuget.org/packages/dotnet-xscgen/
[3]: https://github.com/mganss/XmlSchemaClassGenerator/releases

**Comment by mganss** [comment]
Oops, sorry. Completely forgot. Done now.

**Comment by KretovEM** [comment]
Hello. I try use flag ca|commandArgs like a --ca, --ca=false, --commandArgs, --commandArgs=false on XmlSchemaClassGenerator.Console to disable the command line args comment, but this doesn't work. Help, please

**Comment by mganss** [comment]
You need to append `-` to the flag, e.g. `--ca-`.

**Comment by KretovEM** [comment]
Oh, thank you very much!

**Pull request merged**
