### PR TITLE
clone the children

### PR DESCRIPTION
**Pull request by chrischip**
make sure that when it clones it clones the children recursively as well. I've generated a sample XML which cannot be validated against the schema because of the children were not cloned.

### CODE REVIEW

**Comment by mganss** [comment]
Thanks for the PR. One test failed, though, so I pulled the Clone() method up to the base class InstanceGroup. Please check if your use case is still working.

Also, can you share the schema you are using or better yet, create a new test based on the schema?

**Comment by chrischip** [comment]
Thank you very much it is still working! I have to rewrite this testing
case xsd to remove all the sensitive stuff from our project.

I've tried to look at where is best place to put my xsd and not sure which
directory(may be there \XmlSchemaClassGenerator.Tests\xsd\is24\offer? since
I don't know what the directories are for ) .  I just attach it in this
email so please put that as one of the test case. It fails our unit test
using the old sample generator code and passed with your latest update (
 the Clone()  method in the InstanceGroup).









On Wed, Oct 28, 2015 at 2:36 PM, Michael Ganss <notifications@github.com>
wrote:

> Thanks for the PR. One test failed, though, so I pulled the Clone() method
> up to the base class InstanceGroup. Please check if your use case is still
> working.
>
> Also, can you share the schema you are using or better yet, create a new
> test based on the schema?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mganss/XmlSchemaClassGenerator/pull/11#issuecomment-151830480>
> .
>



-- 
☻/ This is bob. Copy and paste this everywhere
/▌ to vote against e-toll!
/\

**Comment by mganss** [comment]
I've added the test case.

**Comment by chrischip** [comment]
Thank you :)

**Pull request merged**
