### PR TITLE
Add 1 parameter for generator:

### PR DESCRIPTION
**Pull request by MarkoKacprzak**
RemoveUderscoreInPriverMember

### CODE REVIEW

**Comment by mganss** [comment]
Thanks for your contribution. I'm hesitant to merge this. First of all, please correct the spelling of variable names, I see "uderscore" and "priver" several times 😄 I'd prefer DoNotUseUnderscoreInPrivateMemberNames and "nu|noUnderscore".

Regarding the setter: What's the motivation to not heed the advice [Collection properties should be read only](https://msdn.microsoft.com/en-us/library/ms182327.aspx)?

**Comment by MarkoKacprzak** [comment]
My motivation is to use initialize object in one line for example:
`var toSerializationObject = new Request
{
  Header = new Header
  {
    FormId = "test2",
  },
  Data = new ClientRequestData
  {
    Users = new List<UserType>
    {
      new UserType
      {
        Email="test@mail.com",
        Firstname="Jack"
      },
      new UserType
      {
        Email="test@mail.com",
        Firstname="Jack"
      }
    }
  }
}`
Object generated from xsd is just POCO class with additional attribute - we can't setup read only properties etc.

**Comment by mganss** [comment]
You can leave off the `new List<UserType>` and use a [collection initializer](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/object-and-collection-initializers#collection-initializers).

```C#
var toSerializationObject = new Request
{
  Header = new Header
  {
    FormId = "test2",
  },
  Data = new ClientRequestData
  {
    Users =
    {
      new UserType
      {
        Email="test@mail.com",
        Firstname="Jack"
      },
      new UserType
      {
        Email="test@mail.com",
        Firstname="Jack"
      }
    }
  }
}
```

**Comment by mganss** [comment]
There's another typo: `CShaprpKeywords`. I like the `@` prefixing for keywords.

**Comment by MarkoKacprzak** [comment]
Ok so if i can use collection initializer the option for public setter is not necessary. I will remove it from that branch

**Comment by MarkoKacprzak** [comment]
OK I've finished

**Pull request merged**
