### PR TITLE
decimal FractionDigitsRestrictionModel.Value is 0 as integer

### PR DESCRIPTION
**Pull request by kronic**

### CODE REVIEW

**Comment by mganss** [comment]
Thanks. Is this ready to merge?

**Comment by kronic** [comment]
@mganss yes

**Comment by kronic** [comment]
@mganss rollback made changes fix error

**Comment by kronic** [comment]
@mganss  I`m crete new pr

**Comment by mganss** [comment]
@kronic Sorry, I was too quick merging this 😳

**Comment by kronic** [comment]
@mganss  fix [pr](https://github.com/mganss/XmlSchemaClassGenerator/pull/407)

**Pull request merged**
