### PR TITLE
Separated output working (debugging of outputs required)

### PR DESCRIPTION
**Pull request by TomJamesAtDataSummit**
Branched named as per https://github.com/isaacs/github/issues/1125#issuecomment-545628756.

Apparently GitHub doesn't have some fundamental functionality tha GitLab or JIRA does, where a branch can be directly created from an issue or bug and link to a 'project' item

### CODE REVIEW

**Comment by TomJamesAtDataSummit** [comment]
I have added a console project (.NETCore version) named "Entry" which allows me to run the solution locally and alter variables/settings, namely the 'configuration' variables. This project will need to be excluded from CD/CI and possibly the actual repository, once the alterations perform at an acceptable level.

As an overview, 'classes' and 'enums' are creating well structured outputs. 'Interface' and 'struct' objects have methods created for them but currently I don't have a ".xsd" files that activates these areas.

The outputs for 'classes' and 'enums' are generating some fundamental errors, which are mostly due to converting Microsoft `System.Something` variables to base variables. Lists, Dictionaries, Enumerates have a "TODO" comment by them as they are not handled at all. `XmlElementAttribute` is having a range of issue in relation to array type items.

**Comment by mganss** [comment]
I don't think you need to replicate the CodeDom functionality. Perhaps you can create a new `CodeCompileUnit` with new `CodeNamespace`s and add just one type at a time for output in `FileOutputWrite.Write()`:

```c#
var ccu = new CodeCompileUnit();
var cns = new CodeNamespace(cn.Name);

cns.Imports.AddRange(cn.Imports.Cast<CodeNamespaceImport>().ToArray());
cns.Comments.AddRange(cn.Comments);
ccu.Namespaces.Add(cns);

foreach (CodeTypeDeclaration t in cn.Types)
{
    cns.Types.Clear();
    cns.Types.Add(t);
    path = Path.Combine(OutputDirectory, $"{cn.Name}.{t.Name}.cs");
    Configuration?.WriteLog(path);
    WriteFile(path, ccu);
}
```

**Comment by TomJamesAtDataSummit** [comment]
Michael, I implemented your changes and they have had their outputs verified. These have been added via another [commit](https://github.com/mganss/XmlSchemaClassGenerator/pull/177/commits/4d84cb83349680788f70bf8fd95ecfe283f33207).

**Unit Tests**
I can think of a couple of unit tests (e.g. `private string ValidateName(string name)`) to create but am too new to this area to provide full code coverage, I think you'll need to provide some direction and guidance of how and what you want covered.

**Bespoke CodeDom**
FYI, results for the bespoke CodeDom I had started were 95% error free but I hadn't had the full range of "configuration" options tested against them.

The benefit of the bespoke CodeDom was that the code had been optimised for size. The 'using directive' were shortening; class, enum, interface, struct and field declarations, meaning that file sizes were going to be 20%-30% smaller than via the standard CodeCompileUnit CodeDom outputs.

However, the standard CodeCompileUnit CodeDom route is producing error free code for all configurations options except `generator.EnableDataBinding = true;`, which was creating 60 errors in 20,000 lines of code.

**Output & Errors**
This is the code produced via _"CodeCompileUnit CodeDom"_ that had the data-binding errors:
```
namespace itm_types_v7_1
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    using System.Linq;
    using System.ComponentModel;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ScheduleSegment", Namespace="http://xml.hiav.networkrail.co.uk/schema/itm/7.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    internal partial class ScheduleSegment : System.ComponentModel.INotifyPropertyChanged
    {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected virtual void OnPropertyChanged(string propertyName)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private long _id;
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public long Id
        {
            get
            {
                return _id;
            }
            set
            {
                if (!_id.Equals(value))
                {
                    _id = value;
                    OnPropertyChanged(nameof(Id));
                }
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private UnitClassRange _unitClassRange;
        
        public virtual bool ShouldSerializeUnitClassRange()
        {
            return UnitClassRange.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("UnitClassRange", Order=0)]
        public System.Nullable<UnitClassRange> UnitClassRange
        {
            get
            {
                return _unitClassRange;
            }
            set
            {
                if (!_unitClassRange.Equals(value))
                {
                    _unitClassRange = value;
                    OnPropertyChanged(nameof(UnitClassRange));
                }
            }
        }
    }
}
```

This is the debugged and optimised version of the same code:
```
using System;
using System.CodeDom.Compiler;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Linq;
using System.Xml.Serialization;

namespace itm_types_v7_1
{
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ScheduleSegment", Namespace="http://xml.hiav.networkrail.co.uk/schema/itm/7.1")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    internal partial class ScheduleSegment : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void OnPropertyChanged(string propertyName)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }

        [XmlIgnoreAttribute()]
        private long _id;

        [XmlIgnoreAttribute()]
        [KeyAttribute()]
        public long Id
        {
            get
            {
                return _id;
            }
            set
            {
                if (!_id.Equals(value))
                {
                    _id = value;
                    OnPropertyChanged(nameof(Id));
                }
            }
        }

        [XmlIgnoreAttribute()]
        private UnitClassRange _unitClassRange;

        public virtual bool ShouldSerializeUnitClassRange()
        {
            return UnitClassRange.HasValue;
        }

        [XmlElementAttribute("UnitClassRange", Order = 0)]
        public UnitClassRange? UnitClassRange
        {
            get
            {
                return _unitClassRange;
            }
            set
            {
                if (!_unitClassRange.Equals(value))
                {
                    _unitClassRange = (UnitClassRange)value;
                    OnPropertyChanged(nameof(UnitClassRange));
                }
            }
        }
    }
}
```

A surmised snippet of the differences is (6 lines from the end of the file):
`_unitClassRange = (UnitClassRange)value;` (no error)
`_unitClassRange = value;` (error, cast required due to being a nullable variable)

Also, I thought one of the more modern approaches to optional or nullable variables is (16 lines from the end of the file):
`public UnitClassRange? UnitClassRange` (C# 8.0)
`public System.Nullable<UnitClassRange> UnitClassRange` (current output from _"CodeCompileUnit CodeDom"_)

**Next Steps**
1. Advise or remove code that you don't want?
2. Create or link an issue to the `_unitClassRange = value;` nullable casting error?
3. Advise what's to be done for the CI error "continuous-integration/appveyor/pr — AppVeyor build failed"?
4. Indicate if there is additional functionality that has been missed in this branch/pull request?

Regards, Tom.

**Comment by mganss** [comment]
- What is the diff to the single-file output for the classes that fail?
- Unit tests: Run one of the faster demo xsd test cases but with the Generator flag set to single class output files and check that one file per class gets generated. Perhaps take this one:
https://github.com/mganss/XmlSchemaClassGenerator/blob/f310d23bd7db2dbc6d4666577614860dfc2d7552/XmlSchemaClassGenerator.Tests/XmlTests.cs#L200-L206
You'll probably have to make the `OutputWriter` configurable here:
https://github.com/mganss/XmlSchemaClassGenerator/blob/f310d23bd7db2dbc6d4666577614860dfc2d7552/XmlSchemaClassGenerator.Tests/Compiler.cs#L87
Then pass a `FileWatcherOutputWriter` from your test (which records the file names written) and compare the actual file names to a static list of class names that you expect.

**Comment by TomJamesAtDataSummit** [comment]
I ran the Test Explorer which contains 79 tests, of which 20 are failing across a couple of groups; `NullableGenerationTests` and `XmlTests`. I presume that this is why the continuous integration is failing. These can't be **_all_** my errors!!

I saw your sample unit test to determine whether outputs are matching created files (it looks as though you're using xUnit, I haven't written anything in this framework before). I feel that I am not currently capable/experienced to write tests, which will apply rules correctly, rigorously and can be trusted. Sorry, I know that this sounds like I don't want to do the remaining necessary work but it is a capability/experience limitation at this stage.

Furthermore, I have inserted an if...else statement within the public routine:

```
FileOutputWriter.Write(CodeNamespace cn)
{
    var cu = new CodeCompileUnit();
    cu.Namespaces.Add(cn);

    if (Configuration.SeparateClasses == true)
    {
        WriteSeparateFiles(cn);
    }
    else
    {
        var path = Path.Combine(OutputDirectory, cn.Name + ".cs");
        Configuration?.WriteLog(path);
        WriteFile(path, cu);
    }
}

```
but the insert passes to my new routine `private  void FileOutputWriter.WriteSeparateFiles(CodeNamespace cn)`. As this is private routine, xUnit will not allow any test directly on that private routine. Whilst not a criticism of xUnit, this issue highlights the general topic of micro-services and code architecture. Should I be making this method public, in a separate class, etc. I am unsure on your preferred approach.

**Comment by mganss** [comment]
OK, thanks. I'll add tests but it could take a few days.

**Comment by mganss** [comment]
@TomJamesAtDataSummit Can you attach the xsd that produces the errors?

**Comment by LightosTomJ** [comment]
XSD files attached: [Download: 7.2.zip](https://github.com/mganss/XmlSchemaClassGenerator/files/4463651/7.2.zip)

Can you be more specific as to do the error you refer to, I have mentioned 3 in our discussions?

**Comment by mganss** [comment]
Thanks. The failing tests in AppVeyor are unrelated to the generated code. They occur because the `FileOutputWriter` doesn't have the `Configuration` object. I've fixed this on my branch https://github.com/mganss/XmlSchemaClassGenerator/tree/TomJamesAtDataSummit-158-Output-one-file-per-class and the current tests run fine. I do get compiler warnings but these are due to a bug that has already existed:

> 1>Net.SDEF\EquipmentTypeHABD.cs(36,72,36,87): warning CS0108: 'EquipmentTypeHABD.PropertyChanged' hides inherited member 'EquipmentTypeSpecific.PropertyChanged'. Use the new keyword if hiding was intended.
1>Net.SDEF\EquipmentTypeHABD.cs(38,32,38,49): warning CS0114: 'EquipmentTypeHABD.OnPropertyChanged(string)' hides inherited member 'EquipmentTypeSpecific.OnPropertyChanged(string)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword.

I'm not sure if these are the same messages you were referring to above:
  
> However, the standard CodeCompileUnit CodeDom route is producing error free code for all configurations options except generator.EnableDataBinding = true;, which was creating 60 errors in 20,000 lines of code.

Are there any other errors you have encountered? If so, please let me know which xsd files you used and the configuration options.

**Comment by mganss** [comment]
I've manually merged the PR but it doesn't show as merged here for some reason. Perhaps because the original repo is gone?

**Pull request closed without merging**
